services:
  phpinfo:
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
    image: tjchermak/simplilearn-phpinfo:latest
    ports:
      - 80:8080
    volumes:
      - phpinfo:/data
version: '3.8'
volumes:
  phpinfo:
