apiVersion: v1
kind: Pod
metadata:
  name: simplilearn-phpinfo-pod
spec:
  containers:
    - name: simplilearn-phpinfo-container
      image:  tjchermak/simplilearn-phpinfo-container
      command: 
        - "php"
      args:
        - "-f"
        - "index.php"
        - "-S"
        - "0.0.0.0:8080"
